### ISSUE TITLE
An example to compile an `As == x86.AJGT`

### ISSUE THREAD

**Issue by xaionaro** [twitchyliquid64/golang-asm#1]
It seems it does not assemble if I use `obj.Prog{As: x86.AJGT}`, but it does assemble in the same code if I use `obj.AJMP` instead of `x86.AJGT`. It seems like `AJGT` just does not supported in this version. Could you help me to get at least one any valid example of a working `x86.AJGT` `obj.Prog` with a `TYPE_CONST` or/and `TYPE_ADDR` operand?

`obj.Prog{As: x86.AJGT, To: obj.Addr{Type: obj.TYPE_CONST, Offset: 71}}` on `(*asm.Builder).Assemble()` causes empty output and a debug message:
```
invalid instruction: 00000 (<unknown line number>)	JGT	$71
```

`arch == "amd64"`

**Comment by xaionaro** [comment]
Update: It looks like for `x86.AJGT` it is required to use `obj.TYPE_BRANCH`. But still ignores the `Offset`. Investigating...

```
-   00000000  7f 45
+   00000000  7f fe
```

**Comment by twitchyliquid64** [comment]
Have you also set `Pcond` ?

Heres an example of a conditional jump:

https://github.com/go-interpreter/wagon/blob/master/exec/internal/compile/backend_amd64.go#L895

A few things to note:

 - Set type to `obj.TYPE_BRANCH`
 - Unless you are jumping backward, you need to emit the instruction first before filling in `Pcond`
 - Set `Pcond` once the instruction you are jumping to has been allocated

EG:

```go
	jmpNaN := builder.NewProg()
	jmpNaN.As = x86.AJPS // jump parity set. Parity is set for NaN computations.
	jmpNaN.To.Type = obj.TYPE_BRANCH
	builder.AddInstruction(jmpNaN)

// some instructions ...

	writeNaNVal := builder.NewProg()
	writeNaNVal.From.Type = obj.TYPE_CONST
	writeNaNVal.From.Offset = 0
	writeNaNVal.To.Type = obj.TYPE_REG
	writeNaNVal.To.Reg = x86.REG_AX
	writeNaNVal.As = x86.AMOVQ
	jmpNaN.Pcond = writeNaNVal // <--- see what I did there ?
	builder.AddInstruction(writeNaNVal)

```

I'm not sure if you can jump to a constant offset using Go's assembler.

**Comment by xaionaro** [comment]
Yeah. This way works. It veery inconvenient in my case, but much better than nothing :)

Thank you!
